### ISSUE TITLE
Post-Processing on device using Script Node too slow?

### ISSUE THREAD

**Issue by adammpolak** [geaxgx/depthai_yunet#3]
- With the face detection NN I am up to 3 neural nets on the device (also performing person detection and person reid on detections)
- I also want to run another NN downstream for facial recognition which will bring me up to 4
- I have a few dozen sensors running so I cannot send depth frames onto the host to do SpatialLocationCalculation (too much bandwidth)
- So that means I would need to perform the post-processing on the device so I can find the ROI for the SpatialLocationCalculation
- I think that 5 NN are too many for a depthai devicec so I would rather do post-processing in a script node

Have you experimented with this and found any issues?

**Comment by geaxgx** [comment]
It is difficult to say, it is very dependent on the size of the models. I am not specially worried about the number of NNs running on the device. I have already run pipelines with 4 NNs (hand detection + hand landmarks + face tracking + face landmarks). The global FPS you get will be given by slowest model in the pipeline.

**Comment by adammpolak** [comment]
@geaxgx I would like to instead just do the post-processing in a script node so I don't have to export a new NN model everytime I change resolution.

Do you see any issues with performing the post-processing on a script node?

**Comment by geaxgx** [comment]
I guess it would be slower, but can't really say how much slower.

**Comment by adammpolak** [comment]
Thank you
